### ISSUE TITLE
Font HJS589 tidak bisa di download zip

### ISSUE THREAD

**Issue by idrisbtr** [busel7/JWSMurottal#1]
Assalamu'alaikum mas Bony.
untuk font HJS589 sepertinya masih dikunci mas, tidak bisa di download zip.. library yang lain sudah berhasiil download. 
Terimakasih banyak atas share ilmunya. Semoga bermanfaat bagi anak bangsa :+1:

**Comment by busel7** [comment]
Waalaikumsalam, untuk HJS589 belum ada repo khusus, mungkin sementara di copy paste manual, atau bisa didownload secara keseluruhan dari rootnya https://github.com/busel7/Arduino.

Sama sama om, Aamiin.

**Comment by busel7** [comment]
Mudah-mudahan sudah bisa, case ini kami close. Jika masih ada kendala bisa membuka case ini lagi, terimakasih.
