### ISSUE TITLE
Sukses Upload

### ISSUE THREAD

**Issue by Pramfi** [busel7/JWSMurottal#10]
Assalamualaikum Bang Bonny... Setelah 4 hari nonstop cari errornya karena PENASARAN !!! ...  akhirnya ketemu juga terimakasih bang, buat yg msh menemui error saat compiling coba check di bagian Dfplayer.h  karena cuma disitu penyebabnya, 💯% work asalkan library yg dibutuhkan sudah diinstall semua

**Comment by busel7** [comment]
Waalaikumsalam, Alhamdulillah, boleh share lebih detail bagian mana Om? mudah mudahan bisa membantu temen lain yang mengalami masalah yang sama.

**Comment by abdghofur66** [comment]
mohon pencerahannya om.. kendala di websockets nya

**Comment by Hammadar77** [comment]
wa'alaikumsalam, saya juga kendala di df, mohon di share solusinya

**Comment by busel7** [comment]
Mudah-mudahan sudah bisa, case ini kami close. Jika masih ada kendala bisa membuka case ini lagi, terimakasih.

**Comment by miharjo** [comment]
> wa'alaikumsalam, saya juga kendala di df, mohon di share solusinya

Sama gan, saya juga kendala, sudah 2 hari update library dll tetep masih eror juga 😭
