### ISSUE TITLE
Solusi buat WebSocketsServer.h yang error, hanya saja waktu nge-freeze

### ISSUE THREAD

**Issue by abdghofur66** [busel7/JWSMurottal#11]
Assalamu'alaikum, mungkin bisa membantu beberapa teman yang mengalami error **WebSocketsServer.h**, meski install library sesuai petunjuk dari Bang Bonny.
Dari yang saya alami, mungkin perlu install library dari https://www.arduino.cc/reference/en/libraries/websockets/ 
karena setelah install library ini, lancar.
sekian semoga bermanfaat, wassalamu'alaikum

**Comment by busel7** [comment]
Mudah-mudahan sudah bisa, case ini kami close. Jika masih ada kendala bisa membuka case ini lagi, terimakasih.
