### ISSUE TITLE
SUKSES UPLOAD

### ISSUE THREAD

**Issue by Hammadar77** [busel7/JWSMurottal#12]
ASSALAMU'ALAIKUM...........Setelah coba2 cari permasalahannya selama beberapa hari, akhirnya hari ini sukses juga saya upload, permasalahannya ada di dfmini.h yang harus di update, saya pakai dfmini versi makuna 1.0.7 terbaru 
cukup update atau download dfmini versi terbaru saja, Untuk sketch tidak ada kendala
Terimaksih Mas Bonny atas share codingnya, dan semoga dilain waktu masih bersedia untuk share coding atau apk, sehingga bisa sama2 kita tambah kekurangan yang ada

**Comment by busel7** [comment]
Mudah-mudahan sudah bisa, case ini kami close. Jika masih ada kendala bisa membuka case ini lagi, kami tunggu masukan update code pengembangannya terimakasih.
