### ISSUE TITLE
tampilan menu informasi panel p10 blink

### ISSUE THREAD

**Issue by miharjo** [busel7/JWSMurottal#13]
assalamu'alaikum mas...
kemaren sama beli kit modul esp8266 dari olshop mas boni yang sudah di isi file bin.
saya test berjalan normal, cuma yang jadi kendala di tampilan panel p10 sebagian ada yang blink waktu menampilkan informasi 1 dan informasi 2. kira2 kenapa ya mas? mohon petujuknya,, terimakasih .

**Comment by busel7** [comment]
Waalaikumsalam, yg itu karena pakai library DMDESP agar wifi stabil, kalo yg disini pakai HJS589 tidak flicker tapi wifi tidak stabil
