### ISSUE TITLE
belum ketemu

### ISSUE THREAD

**Issue by satriamalam** [busel7/JWSMurottal#16]
saya coba masih error di dfplayer
belum ketemu pak
Arduino: 1.8.12 (Windows 7), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), 4MB (FS:2MB OTA:~1019KB), 2, v2 Lower Memory, Disabled, None, Only Sketch, 115200"

In file included from D:\file\Jws esp\JWS MP3 PAK BONY\JWSMurottal-main\OPREK\JWSMurottal\JWSMurottal.ino:9:0:

C:\Program Files\Arduino\libraries\DFMiniMp3-master\src/DFMiniMp3.h: In instantiation of 'uint16_t DFMiniMp3<T_SERIAL_METHOD, T_NOTIFICATION_METHOD>::listenForReply(uint8_t) [with T_SERIAL_METHOD = HardwareSerial; T_NOTIFICATION_METHOD = Mp3Notify; uint16_t = short unsigned int; uint8_t = unsigned char]':

C:\Program Files\Arduino\libraries\DFMiniMp3-master\src/DFMiniMp3.h:332:38:   required from 'uint16_t DFMiniMp3<T_SERIAL_METHOD, T_NOTIFICATION_METHOD>::getTotalTrackCount(DfMp3_PlaySource) [with T_SERIAL_METHOD = HardwareSerial; T_NOTIFICATION_METHOD = Mp3Notify; uint16_t = short unsigned int]'

sketch\DFPlayer.h:71:62:   required from here

C:\Program Files\Arduino\libraries\DFMiniMp3-master\src/DFMiniMp3.h:511:101: error: no matching function for call to 'Mp3Notify::OnPlayFinished(DFMiniMp3<HardwareSerial, Mp3Notify>&, DfMp3_PlaySources, uint16_t&)'

                         T_NOTIFICATION_METHOD::OnPlayFinished(*this, DfMp3_PlaySources_Usb, replyArg);

                                                                                                     ^

C:\Program Files\Arduino\libraries\DFMiniMp3-master\src/DFMiniMp3.h:511:101: note: candidate is:

In file included from D:\file\Jws esp\JWS MP3 PAK BONY\JWSMurottal-main\OPREK\JWSMurottal\JWSMurottal.ino:26:0:

sketch\DFPlayer.h:31:15: note: static void Mp3Notify::OnPlayFinished(DfMp3_PlaySources, uint16_t)

   static void OnPlayFinished(DfMp3_PlaySources source, uint16_t track)

               ^

sketch\DFPlayer.h:31:15: note:   candidate expects 2 arguments, 3 provided

In file included from D:\file\Jws esp\JWS MP3 PAK BONY\JWSMurottal-main\OPREK\JWSMurottal\JWSMurottal.ino:9:0:

C:\Program Files\Arduino\libraries\DFMiniMp3-master\src/DFMiniMp3.h:515:100: error: no matching function for call to 'Mp3Notify::OnPlayFinished(DFMiniMp3<HardwareSerial, Mp3Notify>&, DfMp3_PlaySources, uint16_t&)'

                         T_NOTIFICATION_METHOD::OnPlayFinished(*this, DfMp3_PlaySources_Sd, replyArg);

                                                                                                    ^

C:\Program Files\Arduino\libraries\DFMiniMp3-master\src/DFMiniMp3.h:515:100: note: candidate is:

In file included from D:\file\Jws esp\JWS MP3 PAK BONY\JWSMurottal-main\OPREK\JWSMurottal\JWSMurottal.ino:26:0:

sketch\DFPlayer.h:31:15: note: static void Mp3Notify::OnPlayFinished(DfMp3_PlaySources, uint16_t)

   static void OnPlayFinished(DfMp3_PlaySources source, uint16_t track)

               ^

sketch\DFPlayer.h:31:15: note:   candidate expects 2 arguments, 3 provided

In file included from D:\file\Jws esp\JWS MP3 PAK BONY\JWSMurottal-main\OPREK\JWSMurottal\JWSMurottal.ino:9:0:

C:\Program Files\Arduino\libraries\DFMiniMp3-master\src/DFMiniMp3.h:519:103: error: no matching function for call to 'Mp3Notify::OnPlayFinished(DFMiniMp3<HardwareSerial, Mp3Notify>&, DfMp3_PlaySources, uint16_t&)'

                         T_NOTIFICATION_METHOD::OnPlayFinished(*this, DfMp3_PlaySources_Flash, replyArg);

                                                                                                       ^

C:\Program Files\Arduino\libraries\DFMiniMp3-master\src/DFMiniMp3.h:519:103: note: candidate is:

In file included from D:\file\Jws esp\JWS MP3 PAK BONY\JWSMurottal-main\OPREK\JWSMurottal\JWSMurottal.ino:26:0:

sketch\DFPlayer.h:31:15: note: static void Mp3Notify::OnPlayFinished(DfMp3_PlaySources, uint16_t)

   static void OnPlayFinished(DfMp3_PlaySources source, uint16_t track)

               ^

sketch\DFPlayer.h:31:15: note:   candidate expects 2 arguments, 3 provided

In file included from D:\file\Jws esp\JWS MP3 PAK BONY\JWSMurottal-main\OPREK\JWSMurottal\JWSMurottal.ino:9:0:

C:\Program Files\Arduino\libraries\DFMiniMp3-master\src/DFMiniMp3.h:524:114: error: no matching function for call to 'Mp3Notify::OnPlaySourceOnline(DFMiniMp3<HardwareSerial, Mp3Notify>&, DfMp3_PlaySources)'

                         T_NOTIFICATION_METHOD::OnPlaySourceOnline(*this, static_cast<DfMp3_PlaySources>(replyArg));

                                                                                                                  ^

C:\Program Files\Arduino\libraries\DFMiniMp3-master\src/DFMiniMp3.h:524:114: note: candidate is:

In file included from D:\file\Jws esp\JWS MP3 PAK BONY\JWSMurottal-main\OPREK\JWSMurottal\JWSMurottal.ino:26:0:

sketch\DFPlayer.h:36:15: note: static void Mp3Notify::OnPlaySourceOnline(DfMp3_PlaySources)

   static void OnPlaySourceOnline(DfMp3_PlaySources source)

               ^

sketch\DFPlayer.h:36:15: note:   candidate expects 1 argument, 2 provided

In file included from D:\file\Jws esp\JWS MP3 PAK BONY\JWSMurottal-main\OPREK\JWSMurottal\JWSMurottal.ino:9:0:

C:\Program Files\Arduino\libraries\DFMiniMp3-master\src/DFMiniMp3.h:529:116: error: no matching function for call to 'Mp3Notify::OnPlaySourceInserted(DFMiniMp3<HardwareSerial, Mp3Notify>&, DfMp3_PlaySources)'

                         T_NOTIFICATION_METHOD::OnPlaySourceInserted(*this, static_cast<DfMp3_PlaySources>(replyArg));

                                                                                                                    ^

C:\Program Files\Arduino\libraries\DFMiniMp3-master\src/DFMiniMp3.h:529:116: note: candidate is:

In file included from D:\file\Jws esp\JWS MP3 PAK BONY\JWSMurottal-main\OPREK\JWSMurottal\JWSMurottal.ino:26:0:

sketch\DFPlayer.h:40:15: note: static void Mp3Notify::OnPlaySourceInserted(DfMp3_PlaySources)

   static void OnPlaySourceInserted(DfMp3_PlaySources source)

               ^

sketch\DFPlayer.h:40:15: note:   candidate expects 1 argument, 2 provided

In file included from D:\file\Jws esp\JWS MP3 PAK BONY\JWSMurottal-main\OPREK\JWSMurottal\JWSMurottal.ino:9:0:

C:\Program Files\Arduino\libraries\DFMiniMp3-master\src/DFMiniMp3.h:534:115: error: no matching function for call to 'Mp3Notify::OnPlaySourceRemoved(DFMiniMp3<HardwareSerial, Mp3Notify>&, DfMp3_PlaySources)'

                         T_NOTIFICATION_METHOD::OnPlaySourceRemoved(*this, static_cast<DfMp3_PlaySources>(replyArg));

                                                                                                                   ^

C:\Program Files\Arduino\libraries\DFMiniMp3-master\src/DFMiniMp3.h:534:115: note: candidate is:

In file included from D:\file\Jws esp\JWS MP3 PAK BONY\JWSMurottal-main\OPREK\JWSMurottal\JWSMurottal.ino:26:0:

sketch\DFPlayer.h:44:15: note: static void Mp3Notify::OnPlaySourceRemoved(DfMp3_PlaySources)

   static void OnPlaySourceRemoved(DfMp3_PlaySources source)

               ^

sketch\DFPlayer.h:44:15: note:   candidate expects 1 argument, 2 provided

In file included from D:\file\Jws esp\JWS MP3 PAK BONY\JWSMurottal-main\OPREK\JWSMurottal\JWSMurottal.ino:9:0:

C:\Program Files\Arduino\libraries\DFMiniMp3-master\src/DFMiniMp3.h:538:71: error: no matching function for call to 'Mp3Notify::OnError(DFMiniMp3<HardwareSerial, Mp3Notify>&, uint16_t&)'

                         T_NOTIFICATION_METHOD::OnError(*this, replyArg);

                                                                       ^

C:\Program Files\Arduino\libraries\DFMiniMp3-master\src/DFMiniMp3.h:538:71: note: candidate is:

In file included from D:\file\Jws esp\JWS MP3 PAK BONY\JWSMurottal-main\OPREK\JWSMurottal\JWSMurottal.ino:26:0:

sketch\DFPlayer.h:24:15: note: static void Mp3Notify::OnError(uint16_t)

   static void OnError(uint16_t errorCode)

               ^

sketch\DFPlayer.h:24:15: note:   candidate expects 1 argument, 2 provided

In file included from D:\file\Jws esp\JWS MP3 PAK BONY\JWSMurottal-main\OPREK\JWSMurottal\JWSMurottal.ino:9:0:

C:\Program Files\Arduino\libraries\DFMiniMp3-master\src/DFMiniMp3.h:552:67: error: no matching function for call to 'Mp3Notify::OnError(DFMiniMp3<HardwareSerial, Mp3Notify>&, uint16_t&)'

                     T_NOTIFICATION_METHOD::OnError(*this, replyArg);

                                                                   ^

C:\Program Files\Arduino\libraries\DFMiniMp3-master\src/DFMiniMp3.h:552:67: note: candidate is:

In file included from D:\file\Jws esp\JWS MP3 PAK BONY\JWSMurottal-main\OPREK\JWSMurottal\JWSMurottal.ino:26:0:

sketch\DFPlayer.h:24:15: note: static void Mp3Notify::OnError(uint16_t)

   static void OnError(uint16_t errorCode)

               ^

sketch\DFPlayer.h:24:15: note:   candidate expects 1 argument, 2 provided

exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by busel7** [comment]
Sudah kami buat video update terkait issue ini silahkan 

Update #1 JWS Murottal OpenSource Ramadhan 1442 Mei 2021 - Kompatibilitas Arduino Library

Video 1 : https://youtu.be/16YHyQWgdu4​
Video 2 : https://youtu.be/bXpgIumwC0Y
