### ISSUE TITLE
Tidak bisa compile error 

### ISSUE THREAD

**Issue by nanaperm12** [busel7/JWSMurottal#17]
ga bisa compile karena eror di bagian sketch jws.h di bagian variable Disp.clear, Disp.setFont dsb seperti info dibawah ini

JWS.h:303:12: error: 'class HJS589' has no member named 'setFont'
       Disp.setFont(ElektronMart5x6);
            ^
JWS.h:309:12: error: 'class HJS589' has no member named 'setFont'
       Disp.setFont(ElektronMart6x8);
            ^
JWS.h:338:5: error: 'disp' was not declared in this scope
     disp.clear();
     ^
JWS.h:341:12: error: 'class HJS589' has no member named 'setFont'
       Disp.setFont(ElektronMart5x6);
            ^
JWS.h:347:12: error: 'class HJS589' has no member named 'setFont'
       Disp.setFont(ElektronMart6x8);
            ^
sketch\JWS.h: In function 'void Iqomah()':
JWS.h:374:12: error: 'class HJS589' has no member named 'setFont'
       Disp.setFont(ElektronMart5x6);
            ^
JWS.h:379:12: error: 'class HJS589' has no member named 'setFont'
       Disp.setFont(ElektronMart6x8);
            ^
JWS.h:393:9: error: 'disp' was not declared in this scope
         disp.clear();
         ^
JWS.h:396:16: error: 'class HJS589' has no member named 'setFont'
           Disp.setFont(ElektronMart5x6);
                ^
JWS.h:402:16: error: 'class HJS589' has no member named 'setFont'
           Disp.setFont(ElektronMart5x6);
                ^
JWS.h:433:10: error: 'class HJS589' has no member named 'setFont'
     Disp.setFont(ElektronMart5x6);
          ^
JWS.h:438:10: error: 'class HJS589' has no member named 'setFont'
     Disp.setFont(ElektronMart6x8);
          ^
sketch\JWS.h: In function 'void TampilJadwalSholat()':
JWS.h:462:10: error: 'class HJS589' has no member named 'drawRect'
     Disp.drawRect(31,0,64,15,0,0);
          ^
JWS.h:479:10: error: 'class HJS589' has no member named 'setFont'
     Disp.setFont(ElektronMart5x6);
          ^
JWS.h:495:12: error: 'class HJS589' has no member named 'drawRect'
       Disp.drawRect(32,0,63,15,0,0);
            ^
JWS.h:496:12: error: 'class HJS589' has no member named 'setFont'
       Disp.setFont(ElektronMart5x6);
            ^
JWS.h:502:14: error: 'class HJS589' has no member named 'drawRect'
         Disp.drawRect(0,0,63,15,0,0);
              ^
sketch\JWS.h: In function 'void TampilTanggal()':
JWS.h:538:10: error: 'class HJS589' has no member named 'setFont'
     Disp.setFont(ElektronMart5x6);
          ^
JWS.h:544:12: error: 'class HJS589' has no member named 'drawRect'
       Disp.drawRect(32,0,63,15,0,0);
            ^
sketch\JWS.h: In function 'void TampilSuhu()':
JWS.h:578:10: error: 'class HJS589' has no member named 'setFont'
     Disp.setFont(ElektronMart5x6);
          ^
JWS.h:584:12: error: 'class HJS589' has no member named 'drawRect'
       Disp.drawRect(32,0,64,15,0,0);
            ^
sketch\JWS.h: In function 'void JamBesar(uint16_t)':
JWS.h:645:10: error: 'class HJS589' has no member named 'drawRect'
     Disp.drawRect(x+15,3+pulse,x+18,11-pulse,0,1);       
          ^
JWS.h:649:10: error: 'class HJS589' has no member named 'drawRect'
     Disp.drawRect(x+15,3,x+18,11,0,0);
          ^
JWS.h:662:10: error: 'class HJS589' has no member named 'setFont'
     Disp.setFont(ElektronMart6x16);
          ^
JWS.h:664:10: error: 'class HJS589' has no member named 'setFont'
     Disp.setFont(ElektronMartArabic6x16);
          ^
JWS.h:666:8: error: 'class HJS589' has no member named 'drawText'
   Disp.drawText(x+1, y - 20, jam);
        ^
JWS.h:670:10: error: 'class HJS589' has no member named 'setFont'
     Disp.setFont(ElektronMart5x6);
          ^
JWS.h:672:10: error: 'class HJS589' has no member named 'setFont'
     Disp.setFont(ElektronMartArabic5x6);
          ^
JWS.h:672:18: error: 'ElektronMartArabic5x6' was not declared in this scope
     Disp.setFont(ElektronMartArabic5x6);
                  ^
JWS.h:674:8: error: 'class HJS589' has no member named 'drawText'
   Disp.drawText(x+20, y - 20, menit);
        ^
JWS.h:678:10: error: 'class HJS589' has no member named 'setFont'
     Disp.setFont(ElektronMart5x6);
          ^
JWS.h:680:10: error: 'class HJS589' has no member named 'setFont'
     Disp.setFont(ElektronMartArabic5x6);
          ^
JWS.h:680:18: error: 'ElektronMartArabic5x6' was not declared in this scope
     Disp.setFont(ElektronMartArabic5x6);
                  ^
JWS.h:682:8: error: 'class HJS589' has no member named 'drawText'
   Disp.drawText(x+20, y - 20 + 8, detik);
        ^
sketch\JWS.h: In function 'void JamBesar2(uint16_t)':
JWS.h:737:10: error: 'class HJS589' has no member named 'drawRect'
     Disp.drawRect(x+14,3+pulse,x+17,11-pulse,0,1);       
          ^
JWS.h:741:10: error: 'class HJS589' has no member named 'drawRect'
     Disp.drawRect(x+14,3,x+18,17,0,0);
          ^
JWS.h:747:5: error: 'disp' was not declared in this scope
     disp.clear();
     ^
JWS.h:752:10: error: 'class HJS589' has no member named 'setFont'
     Disp.setFont(ElektronMart6x16);
          ^
JWS.h:754:10: error: 'class HJS589' has no member named 'setFont'
     Disp.setFont(ElektronMartArabic6x16);
          ^
JWS.h:756:8: error: 'class HJS589' has no member named 'drawText'
   Disp.drawText(x+1, y - 20, jam);
        ^
JWS.h:761:10: error: 'class HJS589' has no member named 'setFont'
     Disp.setFont(ElektronMart6x16);
          ^
JWS.h:763:10: error: 'class HJS589' has no member named 'setFont'
     Disp.setFont(ElektronMartArabic6x16);
          ^
JWS.h:765:8: error: 'class HJS589' has no member named 'drawText'
   Disp.drawText(x+18, y - 20, menit);
        ^
sketch\JWS.h: In function 'void TampilJamKecil()':
JWS.h:788:12: error: 'class HJS589' has no member named 'setFont'
       Disp.setFont(ElektronMart5x6);
            ^
JWS.h:793:12: error: 'class HJS589' has no member named 'setFont'
       Disp.setFont(ElektronMart5x6);
            ^
In file included from E:\projek arduino\JWS\jws bony\JWSMurottal-main\JWSMurottal-main\JWSMurottal\JWSMurottal.ino:31:0:
sketch\JWS.h: In function 'void LogoA(uint32_t)':
JWS.h:816:8: error: 'class HJS589' has no member named 'drawBitmap'
   Disp.drawBitmap(x, 0, LogoA);
        ^
sketch\JWS.h: In function 'void LogoM(uint32_t)':
JWS.h:830:8: error: 'class HJS589' has no member named 'drawBitmap'
   Disp.drawBitmap(x, 0, LogoM);
        ^
sketch\JWS.h: In function 'void animLogoX()':
JWS.h:879:7: error: 'disp' was not declared in this scope
       disp.clear();      
       ^
JWS.h:884:7: error: 'disp' was not declared in this scope
       disp.clear();
       ^
JWS.h:890:14: error: 'class HJS589' has no member named 'width'
   LogoA(Disp.width() - x);
              ^
sketch\JWS.h: In function 'void TeksBerjalanKananKiri()':
JWS.h:909:20: error: 'class HJS589' has no member named 'width'
   int width = Disp.width();
                    ^
JWS.h:912:25: error: 'class HJS589' has no member named 'textWidth'
   int fullScroll = Disp.textWidth(nama1[0]) + width;
                         ^
JWS.h:914:8: error: 'class HJS589' has no member named 'setFont'
   Disp.setFont(ElektronMart6x8);
        ^
JWS.h:919:10: error: 'class HJS589' has no member named 'drawRect'
     Disp.drawRect(0,0,31,15,0,0);
          ^
JWS.h:927:8: error: 'class HJS589' has no member named 'drawRect'
   Disp.drawRect(0,6,Disp.width(),6,1,1);
        ^
JWS.h:927:26: error: 'class HJS589' has no member named 'width'
   Disp.drawRect(0,6,Disp.width(),6,1,1);
                          ^
JWS.h:940:7: error: 'disp' was not declared in this scope
       disp.clear();
       ^
JWS.h:945:10: error: 'class HJS589' has no member named 'drawText'
     Disp.drawText(width - x, 8, nama1[0]);
          ^
sketch\JWS.h: In function 'void TeksJalanInfo1()':
JWS.h:965:20: error: 'class HJS589' has no member named 'width'
   int width = Disp.width();
                    ^
JWS.h:970:10: error: 'class HJS589' has no member named 'drawRect'
     Disp.drawRect(0,0,31,15,0,0);
          ^
JWS.h:976:8: error: 'class HJS589' has no member named 'setFont'
   Disp.setFont(ElektronMart6x8);
        ^
JWS.h:978:25: error: 'class HJS589' has no member named 'textWidth'
   int fullScroll = Disp.textWidth(info1[0]) + width;
                         ^
JWS.h:988:10: error: 'class HJS589' has no member named 'drawText'
     Disp.drawText(width - x, 8, info1[0]);
          ^
sketch\JWS.h: In function 'void TeksJalanInfo2()':
JWS.h:1007:20: error: 'class HJS589' has no member named 'width'
   int width = Disp.width();
                    ^
JWS.h:1012:10: error: 'class HJS589' has no member named 'drawRect'
     Disp.drawRect(0,0,31,15,0,0);
          ^
JWS.h:1018:8: error: 'class HJS589' has no member named 'setFont'
   Disp.setFont(ElektronMart6x8);
        ^
JWS.h:1019:25: error: 'class HJS589' has no member named 'textWidth'
   int fullScroll = Disp.textWidth(info2[0]) + width;
                         ^
JWS.h:1026:7: error: 'disp' was not declared in this scope
       disp.clear();
       ^
JWS.h:1030:10: error: 'class HJS589' has no member named 'drawText'
     Disp.drawText(width - x, 8, info2[0]);
          ^
E:\projek arduino\JWS\jws bony\JWSMurottal-main\JWSMurottal-main\JWSMurottal\JWSMurottal.ino: In function 'void Intro1P()':
JWSMurottal:179:12: error: 'class HJS589' has no member named 'drawRect'
       Disp.drawRect(0,0,31,15,0,0);
            ^
E:\projek arduino\JWS\jws bony\JWSMurottal-main\JWSMurottal-main\JWSMurottal\JWSMurottal.ino: In function 'void DFPlayer()':
JWSMurottal:216:8: error: 'class HJS589' has no member named 'setFont'
   Disp.setFont(ElektronMart6x8);
        ^
JWSMurottal:217:8: error: 'class HJS589' has no member named 'drawText'
   Disp.drawText(1,0, "Volume");
        ^
JWSMurottal:218:8: error: 'class HJS589' has no member named 'drawText'
   Disp.drawText(1,8, vol);
        ^
JWSMurottal:219:8: error: 'class HJS589' has no member named 'drawText'
   Disp.drawText(1,8, vol);
        ^
JWSMurottal:220:8: error: 'class HJS589' has no member named 'drawRect'
   Disp.drawRect(16,8, 16 + (configdf.volume * 24 / 30),14,1,1);
        ^
JWSMurottal:222:8: error: 'class HJS589' has no member named 'drawText'
   Disp.drawText(50,0, "TR");
        ^
JWSMurottal:223:8: error: 'class HJS589' has no member named 'drawText'
   Disp.drawText(43,8, track);  
        ^
E:\projek arduino\JWS\jws bony\JWSMurottal-main\JWSMurottal-main\JWSMurottal\JWSMurottal.ino: In function 'void TestLED()':
JWSMurottal:228:8: error: 'class HJS589' has no member named 'drawRect'
   Disp.drawRect(0, 0, Disp.width(), 16, 1, 1);
        ^
JWSMurottal:228:28: error: 'class HJS589' has no member named 'width'
   Disp.drawRect(0, 0, Disp.width(), 16, 1, 1);
                            ^
Multiple libraries were found for "ESP8266WebServer.h"
 Used: C:\Users\admin\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer
 Not used: E:\Programs\arduino-1.8.13-windows\arduino-1.8.13\libraries\ESP8266WebServer
Multiple libraries were found for "ArduinoJson.h"
 Used: E:\Programs\arduino-1.8.13-windows\arduino-1.8.13\libraries\ArduinoJson
 Not used: C:\Users\admin\Documents\Arduino\libraries\ArduinoJson-5.13.2
Multiple libraries were found for "HJS589.h"
 Used: C:\Users\admin\Documents\Arduino\libraries\HJS589
 Not used: E:\Programs\arduino-1.8.13-windows\arduino-1.8.13\libraries\HJS589
exit status 1
'class HJS589' has no member named 'clear'

**Comment by busel7** [comment]
Sudah kami buat video update terkait issue ini silahkan 

Update #1 JWS Murottal OpenSource Ramadhan 1442 Mei 2021 - Kompatibilitas Arduino Library

Video 1 : https://youtu.be/16YHyQWgdu4​
Video 2 : https://youtu.be/bXpgIumwC0Y
