### ISSUE TITLE
Alhamdulillah sukses upload

### ISSUE THREAD

**Issue by iswansoftware** [busel7/JWSMurottal#19]
ASSALAMU'ALAIKUM WR. WB. 

Terima kasih Mas Bonny sudah open soucekan sketch jwsnya, semoga menjadi amal jariah Mas Bonny. Awalnya saya juga error lib dfpayer, stelah melihat issue di github untuk update dfplayer saya ikuti langsung sukses tanpa merubah sketch sedikitpun. Oia saya mau tambahkan waktu dhuha kayaknya belum ada.

Jazakallahu Khairan Katsiran

**Comment by busel7** [comment]
Sudah kami buat video update selengkapnya silahkan 

Update #1 JWS Murottal OpenSource Ramadhan 1442 Mei 2021 - Kompatibilitas Arduino Library

Video 1 : https://youtu.be/16YHyQWgdu4​
Video 2 : https://youtu.be/bXpgIumwC0Y
