### ISSUE TITLE
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

### ISSUE THREAD

**Issue by alan268** [busel7/JWSMurottal#4]
Assalamualaikum.,  mas Bonny.
Mohon pencerahannya.,  semoga berkah.

sketch\DFPlayer.h:24:15: note:   candidate expects 1 argument, 2 provided
In file included from D:\ABI ALAN\Arduino\JWS Mas Bonny\JWSmurotal200\JWSmurotal200.ino:9:0:
C:\Users\Aylin\Documents\Arduino\libraries\DFMiniMp3-master\src/DFMiniMp3.h:552:67: error: no matching function for call to 'Mp3Notify::OnError(DFMiniMp3<HardwareSerial, Mp3Notify>&, uint16_t&)'
                     T_NOTIFICATION_METHOD::OnError(*this, replyArg);
                                                                   ^
C:\Users\Aylin\Documents\Arduino\libraries\DFMiniMp3-master\src/DFMiniMp3.h:552:67: note: candidate is:
In file included from D:\ABI ALAN\Arduino\JWS Mas Bonny\JWSmurotal200\JWSmurotal200.ino:26:0:
sketch\DFPlayer.h:24:15: note: static void Mp3Notify::OnError(uint16_t)
   static void OnError(uint16_t errorCode)
               ^
sketch\DFPlayer.h:24:15: note:   candidate expects 1 argument, 2 provided
exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

Setelah "compilation" di centang pada File\preferences. 
jadinya sprti ini mas
![image](https://user-images.githubusercontent.com/74606652/103663835-2477e480-4fa4-11eb-98e7-5842743dc35d.png)

**Comment by busel7** [comment]
Sudah coba yang terbaru? baru diupdate sekitar 3 hari lalu, perbaikan error saat compile terutama mengenai library dfplayer. Coba di download lagi sktechnya, jika masih ada error bisa diinfokan kembali.

**Comment by busel7** [comment]
Coba install semua library yg diperlukan, linknya ada dideskripsi

**Comment by busel7** [comment]
Mudah-mudahan sudah bisa, case ini kami close. Jika masih ada kendala bisa membuka case ini lagi, terimakasih.
